style:
    script:
        - python3 -V
        - pip3 install -r requirements.dev.txt --user
        - make style-check

unittest:
    script:
        - pip3 install -r requirements.dev.txt --user
        - make test
        - ls
    artifacts:
        paths:
            - htmlcov

doc:
    script:
        - pip3 install -r requirements.dev.txt --user
        - make doc
    artifacts:
        paths:
            - docs/_build/html

pages:
    stage: deploy
    dependencies:
        - unittest
        - doc
    script:
        - ls
        - mv docs/_build/html public
        - mv htmlcov pubic/cov
    artifacts:
        paths:
            - public

